# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cc_mpd <- function(cdm, dist, ab = FALSE) {
    .Call('_sim_assembly_cc_mpd', PACKAGE = 'sim.assembly', cdm, dist, ab)
}

cc_mpd_v <- function(cdm, dist, ab = FALSE) {
    .Call('_sim_assembly_cc_mpd_v', PACKAGE = 'sim.assembly', cdm, dist, ab)
}

cc_rand_mpd <- function(cdm, dist, ab = FALSE) {
    .Call('_sim_assembly_cc_rand_mpd', PACKAGE = 'sim.assembly', cdm, dist, ab)
}

make_cdm <- function(id, size = 8L, S = 500L) {
    .Call('_sim_assembly_make_cdm', PACKAGE = 'sim.assembly', id, size, S)
}

make_cda <- function(id, size = 8L, S = 500L) {
    .Call('_sim_assembly_make_cda', PACKAGE = 'sim.assembly', id, size, S)
}

scaling_grain <- function(id, dis, ab = TRUE, iter = 100L) {
    .Call('_sim_assembly_scaling_grain', PACKAGE = 'sim.assembly', id, dis, ab, iter)
}

scaling_grain2 <- function(id, dis, ab = TRUE, iter = 100L) {
    .Call('_sim_assembly_scaling_grain2', PACKAGE = 'sim.assembly', id, dis, ab, iter)
}

scaling_pool <- function(cda, dis, ab = TRUE, iter = 100L) {
    .Call('_sim_assembly_scaling_pool', PACKAGE = 'sim.assembly', cda, dis, ab, iter)
}

scaling_coherent <- function(cda, dis, ab = TRUE, iter = 100L) {
    .Call('_sim_assembly_scaling_coherent', PACKAGE = 'sim.assembly', cda, dis, ab, iter)
}

shannon <- function(n) {
    .Call('_sim_assembly_shannon', PACKAGE = 'sim.assembly', n)
}

createCom <- function(env, niche, nu = .001, range = 3L, betaEnv = 1, betaComp = 1, betaAbund = 1, sigma = 5) {
    .Call('_sim_assembly_createCom', PACKAGE = 'sim.assembly', env, niche, nu, range, betaEnv, betaComp, betaAbund, sigma)
}

cc_simCom <- function(com, itNum, report) {
    .Call('_sim_assembly_cc_simCom', PACKAGE = 'sim.assembly', com, itNum, report)
}

cSAR <- function(id, q) {
    .Call('_sim_assembly_cSAR', PACKAGE = 'sim.assembly', id, q)
}

